name: Build

on: [push]

env:
  FABRIC_VERSION: "2.2"
  GOPATH: ${{ github.workspace }}/src/test/fixture

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "8"
          - "11"
          - "17"
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/fabric-sdk-java/fabric-sdk-java/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - run: touch starting_test_uses-checkout_26
      - run: rm starting_test_uses-checkout_26
      - uses: actions/checkout@v3
      - run: touch starting_test_SetupJDKmatrixjavaversion_27
      - run: rm starting_test_SetupJDKmatrixjavaversion_27
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven
      - run: touch starting_test_Integrationtests_33
      - run: rm starting_test_Integrationtests_33
      - name: Integration tests
        run: ./scripts/run-integration-tests.sh
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - run: cp /home/runner/inotify-logs.csv /home/runner/work/fabric-sdk-java/fabric-sdk-java/optimizing-ci-builds-ci-analysis/
        if: always()
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'Priya-it'
          destination-repository-name: 'ci-analyzes'
          target-branch: 'fabric-sdk-java.1672108464'
          target-directory: 'fabric-sdk-java/1672108464/.github/workflows/build/test'

